extn: .png
epochs: 100
im_width: 384
im_height: 288
model_path: output/models/model.pth
log_path: output/models/logs/logs.csv
image_path: dataset/PNG/Original
mask_path: dataset/PNG/Ground Truth
output_path: output/prediction.png
